version: '3.8'
services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      FLASK_ENV: development

  frontend:
    build:
      context: ./src
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    environment:
      NODE_ENV: development
    depends_on:
      - backend