import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import ToasterContext from "./context/ToasterContext";
import AuthProvider from "./context/AuthContext";


const instrumentSans = localFont({
  src: "./fonts/InstrumentSans.woff2",
  variable: "--font-instrument-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSans.variable}  antialiased`}
      >
        <AuthProvider>
        <ToasterContext/>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
